
services:
  postgres:
    image: postgres:17.4-bookworm
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: jdomingu
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./csv:/csvfiles/
      - ./copy:/copy/
    networks:
      - 42ds
  pgadmin:
    image: dpage/pgadmin4:9.2.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.es
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "4040:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - 42ds
    depends_on:
      - postgres

volumes:
  db_data:
  pgadmin_data:

networks:
  42ds: