
services:
  postgres:
    image: postgres:17.4-bookworm
    container_name: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - 42ds

volumes:
  db_data:

networks:
  42ds: