
services:
  postgres:
    image: postgres:17.4-bookworm
    container_name: postgres
    restart: always
    env_file: .env
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./subject:/csvfiles
    networks:
      - 42ds
  pgadmin:
    image: dpage/pgadmin4:9.2.0
    container_name: pgadmin
    env_file: .env
    ports:
      - "4242:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - 42ds
    depends_on:
      - postgres

volumes:
  db_data:
  pgadmin_data:

networks:
  42ds: